# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 803014161cde8873f97ecd834be2b80b8e31923b8f972b8ba379de93de29ec97f62ebe470f3d3b2c05b2b1004640fe163f952fa684ec86cbe3755c156db7c5bb

test:
  secret_key_base: 7e34e9e51a5e6f63b52a3eeb9b5920283bd7127272275fda9a696ad82a50b946d0ad80146bb3f3012865bf28b633614c6cef00dac13607055ebdc6ed051c5a7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
